config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts

  resources "conversations" do
    resources "messages"
  end

  get "/browse" => "browse#browse", as: :browse
  get "matches" => "browse#matches", as: :matches
  post "/approve/:id" => "browse#approve", as: :approve_user
  post "/decline/:id" => "browse#decline", as: :decline_user
  post "get/conversation/:id" => "browse#open_conversation", as: :open_conversation
  root to: "public#home"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many_attached :images
  has_many :messages
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  has_many :messages, dependent: :destroy
  accepts_nested_attributes_for :messages, allow_destroy: true
  validates_presence_of :sender_id, :recipient_id
  validates_uniqueness_of :sender_id, scope: :recipient_id

  scope :between, -> (sender_id, recipient_id) do
    where("(sender_id = ? AND recipient_id = ?) OR (sender_id = ? AND recipient_id = ?)", sender_id, recipient_id, recipient_id, sender_id,)
  end
end

app/models/match.rb
class Match < ApplicationRecord
  validates_uniqueness_of :account_1, scope: :account_2

  scope :between, -> (account_1, account_2) do
    where("(account_1 = ? AND account_2 = ?) OR (account_1 = ? AND account_2 = ?)", account_1, account_2, account_2, account_1,)
  end

  scope :matches_for, -> id do
    matches = where("(account_1 = ? OR account_2 = ?) AND (account_1_approves = ? OR account_2_approves = ?)", id, id, true, true)
  
    account_ids = []
    matches.each do |match|
      new_id = match.account_1 == id ? match.account_2 : match.account_1
      account_ids << new_id 
    end
    Account.where(id: account_ids)
  end

  scope :recommended_matches_for, -> id do
    matches = where("(account_1 = ? AND account_1_approves IS NOT NULL) OR (account_2 = ? AND account_2_approves IS NOT NULL)", id, id)
  
    ignore_ids = [id]
    matches.each do |match|
      new_id = match.account_1 == id ? match.account_2 : match.account_1
      ignore_ids << new_id
    end
    Account.includes(:images_attachments).where.not(id: ignore_ids).order(id: :asc).limit(10)
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :account

  validates_presence_of :body, :account_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise, if: :devise_controller?

  private
  def configure_devise
    devise_parameter_sanitizer.permit(:account_update, keys: [ :first_name, :last_name, :username, :education, :location, :description, images: [] ])
  end
end

app/controllers/browse_controller.rb
class BrowseController < ApplicationController
  def browse
    @matches = Match.matches_for(current_account.id)
    @users = Match.recommended_matches_for(current_account.id )
    @conversations = Conversation.includes(:messages).where("conversations.sender_id = ? OR conversations.recipient_id = ?", current_account.id, current_account.id)
  end

  def approve
    account_id = params[:id]
    match = Match.between( account_id, current_account.id )
    
    if match.present?
      match = match.first

      if match.account_1 == current_account.id
        match.account_1_approves = true
      else
        match.account_2_approves = true
      end
    
    else
      match = Match.new(account_1: current_account.id, account_2: account_id, account_1_approves: true)
    end
  end

  def decline
    account_id = params[:id]
    match = Match.between( account_id, current_account.id )
    
    if match.present?
      match = match.first

      if match.account_1 == current_account.id
        match.account_1_approves = false
      else
        match.account_2_approves = false
      end
    else
      match = Match.new(account_1: current_account.id, account_2: account_id, account_1_approves: false)
    end
  end

  def open_conversation
    id = params[:id]
    @profile = Account.find(id)
    match = Match.between(current_account.id, id)
    @match = match.first if match.present?
    
    conversation = Conversation.between(id, current_account.id)
    
    @conversation = conversation.size > 0 ? conversation.first : Conversation.new
    @messages = @conversation.messages.includes(account: :images_attachments) if @conversation.persisted?
    @message = @conversation.messages.build
    
    if @profile.present?

      respond_to do |format|
        format.js{
          render "browse/conversation"
        }
      end
    end
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController

def create
  @conversation = Conversation.new(conversation_params)
  @conversation.sender_id = current_account.id
  @conversation.messages.first.account_id = current_account.id
end

def update
  @conversation = Conversation.find(params[:id])
    
  respond_to do |format|
    format.js{
      if @conversation.update(conversation_params)
        @messages = @conversation.messages
        render "browse/conversation_messages"
      else
        
      end
      }
  end
end

  private
  def conversation_params
    params.require(:conversation).permit(:recipient_id, messages_attributes: [:body, :account_id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
end

app/controllers/public_controller.rb
class PublicController < ApplicationController
  def home
    redirect_to browse_path if account_signed_in?
  end
end

app/helpers/accounts_helper.rb
module  AccountsHelper
  def profile_thumbnail account
    image_tag account.images.first, width: "40px", height: "40px", class:" float-left profile-thumb rounded-circle mr-3" if account.images.any?
  end

  def get_account_from_conversation conversation
    matched_account_id = conversation.sender_id == current_account.id ? conversation.recipient_id : conversation.sender_id
    @matches.select{ |account| account.id == matched_account_id }.first
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/browse/_conversation.html.erb
<div class="row">
  <div class="col-12 top-bar">
    <div id="close-conversation">
      <i class="fa fa-times fa-2x text-muted float-right"></i>
    </div>
    <%= link_to image_tag(@profile.images.first, width: "40px", height: "40px", class:" float-left profile-thumb rounded-circle mr-3")  %>
    <p class="text-muted mt-2">You matched with <span><%= @profile.first_name %>on <%= @match.created_at.strftime("%Y/%m/%d") %></span>
  </div>
</div>

<div class="row">
  <div class="col-12 text-center">
    <% if @conversation.new_record? %>
      <div id="initiate-conversation">
        <p class="mt-3">You matched with <span><%= @profile.first_name %></span> <%= time_ago_in_words @match.created_at %> ago.</p>
          <%= link_to image_tag(@profile.images.first, width: "200px", height: "200px", class:"rounded-circle mt-3 mb-5")  %>
          <p>Send them a message and make them smile :) </p>
      </div>
    <% end %>
    <div id="conversation-messages"><%= render partial: "browse/messages" unless @conversation.new_record? %></div>
  </div>
</div>

<div class="row">
  <div class="col-sm-12 mt-5 bottom-bar">
    <%= render partial: "browse/new_conversation" %>
  </div>
</div>

app/views/browse/_matches.html.erb
<div class="row">
  <% @matches.each do |match| %>
    <div class="col-sm-4 mt-3">
      <div class="match-tile rounded" data-id="<%= match.id %>"<% if match.images.attached? %>style="background-image: url('<%= url_for match.images.first %>')"<% end %>>
        <p class="text-white"><%= match.first_name %></p>
      </div>
    </div>
  <% end %>
</div>

app/views/browse/_messages.html.erb
<% @messages.each do |message|%>
  <% if message.persisted? %>
    <% if message.account_id == current_account.id %> 
      <%= render partial: "messages/sent_by_me", locals: {message: message} %>  
    <% else %>
      <%= render partial: "messages/sent_by_match", locals: {message: message} %>
    <% end  %>
  <% end %>
<% end %>

app/views/browse/_new_conversation.html.erb
<%= form_with model: @conversation do |f| %>
  <%= f.hidden_field :recipient_id, value: @profile.id%>
  <div class="input-group bottom-bar">
    <%= f.fields_for :messages, @message do |message_form| %>
      <%= message_form.hidden_field :account_id, value: current_account.id %>
      <%= message_form.text_field :body, placeholder: "Enter your message and press send", id:"message-input", class:"form-control form-control-lg"%>
    <% end %>
    <div class="input-group-append">
      <input type="submit" name="submit" value="Send" class="btn btn-success btn-lg pl-5 pr-5">
    </div>
  </div>
<% end %>

app/views/browse/browse.html.erb
<div class="row">
  <div class="col-md-4 bg-white">
    <%= render "layouts/profile_bar" %>
    <ul class="nav nav-match-sidebar mb-3 ml-4 mt-3" id="pills-tab" role="tablist">
      <li class="nav-item" role="presentation">
        <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Matches</a>
      </li>
      <li class="nav-item" role="presentation">
        <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-messages" role="tab" aria-controls="pills-profile" aria-selected="false">Messages</a>
      </li>
    </ul>
    <div class="tab-content ml-2" id="pills-tabContent">
      <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        <%= render "browse/matches" %>
      </div>
      <div class="tab-pane fade ml-2" id="pills-messages" role="tabpanel" aria-labelledby="pills-profile-tab">
        <div class="col">
          <%= render partial: "conversations/list" %>
        </div>
      </div>
    </div>
  </div>
  
  <div class="col-9 col-md-8">
    <ul id="slides">
      <% @users.each_with_index do |user, i| %>
      <li class="slide <%= 'showing' if i == 0 %>" data-id="<%= user.id %>">
        <div class="image-carousel" style="background-image: url('<%= url_for user.images.first %>')">
        </div>
        <div class="user-details">
          <span class="user-name"><%= user.first_name %></span><br />
            <i class="fa fa-graduation-cap mr-1"></i><%= user.education %><br />
            <i class="fa fa-map-marker mr-3"></i><%= user.location %><br />
          <span class="profile-info fa-stack">
            <i class="fa fa-circle text-white fa-stack-2x"></i>
            <i class="fa fa-info text-dark fa-stack-1x"></i>
          </span>
        </div>
        <div class="more-details text-dark">
          <%= simple_format user.description %>
        </div>
      </li>
      <% end %>
    </ul>

    <div id="slide-controls">
      <div id="decline" class="d-inline-block fa-stack fa-2x">
        <i class="fa fa-circle fa-stack-2x text-white"></i>
        <i class="fa fa-times fa-stack-1x text-danger"></i>
      </div>
      <div id="approve" class="d-inline-block fa-stack fa-2x">
        <i class="fa fa-circle fa-stack-2x text-white"></i>
        <i class="fa fa-heart fa-stack-1x text-success"></i>
      </div>
    </div>
      <div id="conversation"></div>
  </div>
</div>

app/views/browse/conversation.js.erb
$("#conversation").html("<%= escape_javascript(render partial: 'browse/conversation') %>").show();


$("#close-conversation").on("click", function () {
  $("#conversation").hide();
});

app/views/browse/conversation_messages.js.erb
$("#initiate-conversation").hide();
$("#conversation-messages").html("<%= escape_javascript(render partial: "browse/messages")%>");
$("#message-input").val("");

app/views/conversations/_list.html.erb
<% if @conversations.size > 0 %>
  <% @conversations.each do |conversation| account = get_account_from_conversation(conversation)%>
    <% if account.present? %>
      <div class="row">
        <div class="col open-conversation" data-id="<%= account.id %>">
          <%= profile_thumbnail account %>
          <strong><%= account.first_name %></strong><br />
          <%= simple_format conversation.messages.last.body %>
        </div>
      </div>
    <% end %>
  <% end %>
<% else %>
  <p>No messages to display.</p>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top">
    <div class="row">
      <div class="col-12 col-md">
        <small class="d-block mb-3 text-muted">© 2017-2020</small>
      </div>
      <div class="col-6 col-md">
        <h5>Features</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Cool stuff</a></li>
          <li><a class="text-muted" href="#">Random feature</a></li>
          <li><a class="text-muted" href="#">Team feature</a></li>
          <li><a class="text-muted" href="#">Stuff for developers</a></li>
          <li><a class="text-muted" href="#">Another one</a></li>
          <li><a class="text-muted" href="#">Last time</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Resource</a></li>
          <li><a class="text-muted" href="#">Resource name</a></li>
          <li><a class="text-muted" href="#">Another resource</a></li>
          <li><a class="text-muted" href="#">Final resource</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>About</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Locations</a></li>
          <li><a class="text-muted" href="#">Privacy</a></li>
          <li><a class="text-muted" href="#">Terms</a></li>
        </ul>
      </div>
    </div>
  </footer>

app/views/layouts/_nav.html.erb
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 bg-white border-bottom shadow-sm">
  <h5 class="my-0 mr-md-auto font-weight-normal">Maching App</h5>  
  
  <% if account_signed_in? %>
  <nav class="my-2 my-md-0 mr-md-3">
    <%= link_to "Browse", browse_path, class: "text-dark mr-3"%>
    <%= link_to "My Matches", matches_path, class: "text-dark mr-3"%>
    <%= link_to "Settings", edit_account_registration_path, class: "text-dark "%>
  </nav>  
  <%= link_to "Sign out", destroy_account_session_path, method: :delete, class:"btn btn-secondary mr-2" %>
  <% else %>
  <nav class="my-2 my-md-0 mr-md-3">
    <a class="p-2 text-dark" href="#">Features</a>
    <a class="p-2 text-dark" href="#">Enterprise</a>
    <a class="p-2 text-dark" href="#">Support</a>
  </nav>    
    <%= link_to "Sign in", new_account_session_path, class:"btn btn-secondary mr-2" %>
    <%= link_to "Sign up", new_account_registration_path, class:"btn btn-outline-primary" %>
  <% end %>
</div>

app/views/layouts/_profile_bar.html.erb
<div class="bg-danger profile-bar">
  <%= link_to "Sign Out", destroy_account_session_path, method: :delete, class: "float-right text-white mt-2" %>
  <%= link_to image_tag(current_account.images.first, width: "40px", height: "40px", class:" float-left profile-thumb rounded-circle mr-3"), edit_account_registration_path  %>
  <%= link_to "My Profile", edit_account_registration_path, class: "my-profile text-white" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MatchingApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= render "layouts/nav" unless account_signed_in? %>
    <div class="container-fluid p-0 bg-light">
      <%# <p class="notice"><%= notice %>
      <%# <p class="alert"><%= alert %>
      <%= yield %>
    </div>
    <%= render "layouts/footer" unless account_signed_in? %>
  </body>
</html>

app/views/messages/_sent_by_match.html.erb
<div class="row mb-2">
  <div class="col-sm-2 col-lg-1 text-right">
    <%= image_tag message.account.images.first, class: "rounded-circle", width: "40px", height: "40px" if message.account.images.any? %>
  </div>
  <div class="col-sm-10 col-lg-11">
    <div class="float-left p-2 rounded conversation-message">
      <%= simple_format message.body %>
    </div>  
  </div>
</div> 

app/views/messages/_sent_by_me.html.erb
<div class="row mb-2 sent-by-me">
  <div class="col-12">
    <div class="float-right p-2 rounded conversation-message">
      <%= simple_format message.body %>
    </div>  
  </div>
</div> 